### ISSUE TITLE
Update asker to 1.1.0

### ISSUE THREAD

**Issue by vitkarpov** [nodules/vow-asker#7]
There's a new version which contains an important feature: time field within an error object. Thanks!

**Comment by narqo** [comment]
As we use caret ranged dependencies (`^1.0.0`), `asker@1.1.0` will be installed without any additional changes in vow-asker.

~~~
› npm --prefix=/tmp i vow-asker
/tmp
└─┬ vow-asker@1.0.0
  ├─┬ asker@1.1.0
  │ ├── asker-advanced-agent@0.1.0
  │ ├── contimer@1.0.1
  │ ├── object-assign@4.0.1
  │ ├── retry@0.8.0
  │ ├── terror@1.3.0
  │ └── unzip-response@1.0.0
  └── vow@0.4.12
~~~
